version: "3"

services:
  db-multi:
    image: mysql:latest
    container_name: db-multi-$env
    environment:
      MYSQL_ROOT_PASSWORD: training-2023
      MYSQL_DATABASE: users
      MYSQL_USER: training
      MYSQL_PASSWORD: training_pw
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: unless-stopped
    ports:
      - "3307:3306"
    networks:
      - app-network-multi-$env

  app-multi:
    image: thaihmcsp/nodejs-multi-env:{tag}
    build:
      context: nodejs/.
      dockerfile: Dockerfile
    container_name: app-multi-$env
    depends_on:
      - db-multi-$env
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: training
      DB_PASSWORD: training_pw
      DB_DATABASE: users
    networks:
      - app-network-multi-$env

networks:
  app-network-multi-$env:
    external: true
